import { BOOK_PACK_FORMAT_VERSION, type BookPack } from '@soombook/book-schema';

export function createDemoBookPack(): BookPack {
  return {
    manifest: {
      formatVersion: BOOK_PACK_FORMAT_VERSION,
      packVersion: '0.3.0',
      id: 'book-tiger-demo',
      slug: 'tiger-demo',
      title: '호랑이가 그림에서 사라졌다',
      status: 'fixture',
      locale: 'ko-KR',
      minReaderVersion: '0.1.0',
      entrySceneId: 'scene-cover',
      sceneOrder: ['scene-cover', 'scene-search', 'scene-reason', 'scene-connect'],
      completion: {
        requiredConnectionIds: ['connection-museum'],
        requiredInteractionIds: ['interaction-find-tail'],
        requiredReasoningIds: ['reasoning-tiger-path'],
        review: {
          recallPrompt: '호랑이는 어느 길로 왜 갔을까요? 어떤 두 단서가 그 길을 알려 주었나요?',
          recallCards: [
            {
              id: 'recall-path-clues',
              text: '큰 발자국과 눕혀진 풀잎이 소나무 길을 가리켰어요.',
            },
            {
              id: 'recall-text-picture',
              text: '호랑이는 그림 밖 소나무 향기가 궁금해 소나무 길을 걸었어요.',
            },
            {
              id: 'recall-looking',
              text: '그림을 오래 보면 보이지 않던 이야기가 나타나요.',
            },
          ],
          treasure: {
            interactionId: 'interaction-find-tail',
            title: '먹빛 숲에서 찾은 보물',
            body: '큰 발자국과 눕혀진 풀잎이 같은 길에 있었어요. 바위 뒤에서는 줄무늬 꼬리가 보였어요.',
          },
        },
      },
    },
    book: {
      audience: {
        grade: 3,
        independentReadingMinutes: 8,
      },
      summary:
        '그림에서 사라진 호랑이의 흔적을 읽고, 찾고, 근거를 말하고, 박물관 질문으로 연결하는 기능 검증용 이야기입니다.',
      learningGoals: [
        '이야기의 단서를 문장에서 찾는다.',
        '찾은 단서를 근거로 선택 이유를 말한다.',
        '이야기 속 대상을 현실의 문화 질문과 연결한다.',
      ],
      readingModes: ['direct'],
      privacy: {
        childAccountRequired: false,
        remoteTelemetryDefault: false,
      },
    },
    scenes: [
      {
        id: 'scene-cover',
        kind: 'cover',
        title: '빈 그림의 초대',
        shortLabel: '시작',
        instruction: '표지를 열고 사라진 호랑이의 이야기를 시작하세요.',
        narration: '달빛이 비치는 밤, 오래된 그림 한가운데에 호랑이 모양의 빈자리가 생겼어요.',
        visual: {
          motif: 'paper',
          palette: 'ink',
          alt: '달빛 아래 펼쳐진 종이와 호랑이 모양의 빈자리',
          truthStatus: 'fixture',
          decorations: ['moon', 'mountains', 'tiger', 'child'],
        },
        textBlocks: [
          {
            id: 'text-cover-1',
            heading: '수상한 밤',
            body: '그림을 지키던 아이 숨이는 빈자리 곁에서 반짝이는 붓 자국을 발견했어요.',
          },
        ],
        interactionIds: [],
        reasoningIds: [],
        connectionIds: [],
      },
      {
        id: 'scene-search',
        kind: 'investigation',
        title: '먹빛 숲의 단서',
        shortLabel: '찾기',
        instruction: '세 길의 발자국과 풀잎을 비교해 편지와 맞는 길을 찾아보세요.',
        narration:
          '먹빛 숲에는 연못, 소나무, 마을로 이어진 세 길이 있었어요. 편지에는 큰 발자국과 눕혀진 풀이 함께 있는 길을 살펴보라고 적혀 있었지요.',
        visual: {
          motif: 'painting',
          palette: 'indigo',
          alt: '연못, 소나무, 마을로 갈라진 세 길과 서로 다른 발자국',
          truthStatus: 'fixture',
          decorations: ['moon', 'mountains', 'pine', 'tiger'],
          baseAssetId: 'asset-tiger-base',
          detailAssetId: 'asset-tiger-detail',
        },
        textBlocks: [
          {
            id: 'text-search-1',
            heading: '첫 번째 흔적',
            body: '길에는 커다란 발자국이 있었고, 소나무 아래 풀잎은 한쪽으로 눕혀져 있었어요.',
          },
          {
            id: 'text-search-unlocked',
            heading: '렌즈가 밝힌 것',
            body: '바위 뒤 줄무늬는 붓 자국이 아니라 호랑이의 꼬리였어요.',
          },
        ],
        interactionIds: ['interaction-find-tail'],
        reasoningIds: [],
        connectionIds: [],
      },
      {
        id: 'scene-reason',
        kind: 'reasoning',
        title: '호랑이는 어디로 갔을까',
        shortLabel: '생각',
        instruction: '찾은 단서와 호랑이의 편지를 함께 보고 가장 알맞은 설명을 고르세요.',
        narration:
          '소나무 길 끝에는 호랑이가 남긴 편지가 있었어요. 그림 밖 소나무 향기가 궁금해 잠깐 숲을 걸었다고 쓰여 있었지요.',
        visual: {
          motif: 'moon',
          palette: 'amber',
          alt: '세 갈래 길 위에서 단서를 비교하는 숨이',
          truthStatus: 'fixture',
          decorations: ['moon', 'mountains', 'pine', 'child'],
        },
        textBlocks: [
          {
            id: 'text-reason-1',
            heading: '단서를 모아 보기',
            body: '큰 발자국과 눕혀진 풀잎은 호랑이가 간 길을 알려 주고, 편지는 그림을 떠난 까닭을 알려 주었어요.',
          },
        ],
        interactionIds: [],
        reasoningIds: ['reasoning-tiger-path'],
        connectionIds: [],
      },
      {
        id: 'scene-connect',
        kind: 'connection',
        title: '그림 밖으로 이어진 질문',
        shortLabel: '연결',
        instruction: '연결 카드를 열고 현실의 그림을 볼 때 던질 질문을 만나세요.',
        narration:
          '호랑이는 그림 속 제자리로 돌아왔어요. 숨이는 이제 그림을 볼 때 무엇을 살펴야 할지 궁금해졌어요.',
        visual: {
          motif: 'museum',
          palette: 'jade',
          alt: '완성된 호랑이 그림 앞에서 질문 카드를 든 숨이',
          truthStatus: 'fixture',
          decorations: ['moon', 'mountains', 'tiger', 'child'],
        },
        textBlocks: [
          {
            id: 'text-connect-1',
            heading: '다음 탐험을 위한 질문',
            body: '그림 속 동물의 자세, 배경, 표정을 차례로 살펴보면 어떤 이야기가 떠오를까요?',
          },
        ],
        interactionIds: [],
        reasoningIds: [],
        connectionIds: ['connection-museum'],
      },
    ],
    interactions: [
      {
        id: 'interaction-find-tail',
        sceneId: 'scene-search',
        kind: 'findClue',
        prompt: '세 길의 발자국과 풀잎을 비교해 편지와 맞는 길을 찾아보세요.',
        accessibleName: '먹빛 숲의 세 길 살펴보기',
        inputAdapters: ['lens', 'regionTap', 'keyboard', 'linearExplore'],
        pointerTarget: {
          shape: 'ellipse',
          centerXPercent: 75,
          centerYPercent: 66,
          radiusXPercent: 18,
          radiusYPercent: 20,
        },
        choices: [
          { id: 'path-pond', label: '연못 길: 작은 새 발자국과 꼿꼿한 풀' },
          { id: 'path-pine', label: '소나무 길: 큰 발자국과 한쪽으로 눕혀진 풀' },
          { id: 'path-village', label: '마을 길: 둥근 고양이 발자국과 꼿꼿한 풀' },
        ],
        correctChoiceId: 'path-pine',
        successFeedback:
          '소나무 길의 두 단서가 편지와 맞았어요. 바위 뒤에서는 줄무늬 꼬리도 보였어요.',
        retryFeedback: '괜찮아요. 편지에 나온 발자국 크기와 풀잎 방향을 함께 살펴보세요.',
        unlockTextIds: ['text-search-unlocked'],
        hintSteps: [
          { kind: 'word', text: '발자국의 크기와 풀잎의 모양을 함께 살펴보세요.' },
          { kind: 'direction', text: '그림의 오른쪽으로 눈길을 옮겨 보세요.' },
          { kind: 'area', text: '소나무 옆 길과 둥근 바위 주변을 살펴보세요.' },
          {
            kind: 'direct',
            text: '큰 발자국과 한쪽으로 눕혀진 풀잎이 있는 소나무 길을 골라 보세요.',
          },
        ],
        completion: {
          minimumDiscoveries: 1,
        },
      },
    ],
    reasoningPrompts: [
      {
        id: 'reasoning-tiger-path',
        sceneId: 'scene-reason',
        prompt: '호랑이가 떠난 길과 까닭을 단서에 맞게 이은 것은 무엇일까요?',
        choices: [
          { id: 'choice-pond', label: '작은 새 발자국이 있는 연못 길, 목이 말라서' },
          {
            id: 'choice-pine',
            label: '큰 발자국과 눕혀진 풀이 있는 소나무 길, 그림 밖 향기가 궁금해서',
          },
          { id: 'choice-village', label: '고양이 발자국이 있는 마을 길, 먹이를 찾아서' },
        ],
        correctChoiceId: 'choice-pine',
        evidenceInteractionIds: ['interaction-find-tail'],
        successFeedback:
          '큰 발자국과 눕혀진 풀잎은 소나무 길을, 편지는 호랑이가 떠난 까닭을 알려 주었어요.',
        retryFeedback: '괜찮아요. 찾기 장면의 두 특징과 호랑이의 편지를 함께 떠올려 보세요.',
      },
    ],
    connectionCards: [
      {
        id: 'connection-museum',
        sceneId: 'scene-connect',
        title: '그림을 오래 보는 세 가지 질문',
        body: '이 카드는 기능 검증용 가상 설명입니다. 실제 작품을 볼 때에는 무엇이 보이는지, 어떤 근거로 그렇게 생각했는지, 더 알아보고 싶은 것이 무엇인지 차례로 질문해 보세요.',
        sourceClaimIds: ['claim-fixture-observation'],
        truthStatus: 'fixture',
      },
    ],
    rights: [
      {
        id: 'rights-fixture-story',
        subjectType: 'text',
        subjectId: 'book-tiger-demo',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트의 기능 검증용 창작 픽스처',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes: '실제 문화유산 자료가 아니며 출판용 원고로 승인되지 않았습니다.',
        coveredSubjectIds: ['book-tiger-demo'],
      },
      {
        id: 'rights-fixture-art',
        subjectType: 'visual',
        subjectId: 'asset-css-tiger-scene',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트의 CSS 기반 기능 검증용 시각물',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes: '외부 이미지 파일을 사용하지 않습니다.',
        coveredSubjectIds: ['asset-css-tiger-scene'],
      },
      {
        id: 'rights-fixture-claim',
        subjectType: 'claim',
        subjectId: 'claim-fixture-observation',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트의 기능 검증용 문장',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes: '사실 정보로 출판할 수 없는 가상 설명입니다.',
        coveredSubjectIds: ['claim-fixture-observation'],
      },
      {
        id: 'rights-fixture-art-files',
        subjectType: 'visual',
        subjectId: 'asset-tiger-scene-files',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트가 직접 만든 기능 검증용 SVG 시각물',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes: '외부 원본을 사용하지 않은 창작 fixture base와 detail 자산입니다.',
        coveredSubjectIds: ['asset-tiger-base', 'asset-tiger-detail'],
      },
    ],
    claims: [
      {
        id: 'claim-fixture-observation',
        statement: '기능 검증용 질문 카드는 실제 문화유산 사실을 주장하지 않는다.',
        sourceTitle: 'Soombook 내부 기능 검증 픽스처',
        sourceUrl: null,
        checkedAt: '2026-08-09',
        reviewStatus: 'fixture',
        kind: 'fixture',
        scope: 'fixture',
        caveats: ['실제 문화유산 사실이나 해석으로 사용할 수 없습니다.'],
        sourceEvidenceRefs: [],
        audienceTextRefs: ['text-connect-1'],
        recheckTriggers: ['질문 카드 문구 변경'],
      },
    ],
    assets: [
      {
        id: 'asset-css-tiger-scene',
        kind: 'cssArtwork',
        path: null,
        rightsRecordId: 'rights-fixture-art',
        integrity: null,
        alt: 'CSS 도형으로 만든 기능 검증용 호랑이 탐험 장면',
        role: 'storyIllustration',
        truthStatus: 'fixture',
        derivedFromAssetIds: [],
      },
      {
        id: 'asset-tiger-base',
        kind: 'image',
        path: 'assets/tiger-base.svg',
        rightsRecordId: 'rights-fixture-art-files',
        integrity: 'sha256-2d38a0d2ea4274b8e5a620b8ddaeb6f44949c42d2bd654766faea7d43aafcb63',
        alt: '달빛 아래 세 갈래 길과 큰 발자국이 있는 먹빛 숲',
        role: 'storyIllustration',
        truthStatus: 'fixture',
        derivedFromAssetIds: [],
      },
      {
        id: 'asset-tiger-detail',
        kind: 'image',
        path: 'assets/tiger-detail.svg',
        rightsRecordId: 'rights-fixture-art-files',
        integrity: 'sha256-a193987a9708853514c59a36d1153061962294bbda05e6c154c65d4cae4a3b70',
        alt: '큰 발자국과 눕혀진 풀잎, 바위 뒤 줄무늬 꼬리의 상세 장면',
        role: 'storyIllustration',
        truthStatus: 'fixture',
        derivedFromAssetIds: ['asset-tiger-base'],
      },
    ],
    audioTracks: [],
  };
}
