import { BOOK_PACK_FORMAT_VERSION, type BookPack } from '@soombook/book-schema';

export function createLanternDemoBookPack(): BookPack {
  return {
    manifest: {
      formatVersion: BOOK_PACK_FORMAT_VERSION,
      packVersion: '0.1.0',
      id: 'book-lantern-demo',
      slug: 'lantern-demo',
      title: '바람이 숨긴 등불 지도',
      status: 'internal',
      locale: 'ko-KR',
      minReaderVersion: '0.1.0',
      entrySceneId: 'lantern-cover',
      sceneOrder: [
        'lantern-cover',
        'lantern-map',
        'lantern-search',
        'lantern-reason',
        'lantern-connect',
      ],
      completion: {
        requiredConnectionIds: ['lantern-connection'],
        requiredInteractionIds: ['lantern-find-ribbon'],
        requiredReasoningIds: ['lantern-reasoning'],
        review: {
          recallPrompt: '등불은 어느 길에 있었나요? 어떤 두 단서가 그 길을 알려 주었나요?',
          recallCards: [
            { id: 'lantern-recall-ribbons', text: '흰 리본 두 개가 돌담 길을 가리켰어요.' },
            { id: 'lantern-recall-knot', text: '별 모양 매듭이 등불 꾸러미와 같은 표시였어요.' },
          ],
          treasure: {
            interactionId: 'lantern-find-ribbon',
            title: '바람 지도에서 찾은 보물',
            body: '돌담 아래 흰 리본 두 개와 별 모양 매듭이 같은 길을 알려 주었어요.',
          },
        },
      },
    },
    book: {
      audience: { grade: 3, independentReadingMinutes: 7 },
      summary:
        '바람에 흩어진 지도 조각을 읽고, 리본과 매듭을 비교해 등불이 있는 길을 찾는 비공개 제작 검증 이야기입니다.',
      learningGoals: [
        '그림에서 반복되는 특징을 찾는다.',
        '두 단서를 묶어 선택의 근거를 설명한다.',
        '관찰 질문을 다음 그림에 적용한다.',
      ],
      readingModes: ['direct', 'guided', 'listen'],
      privacy: { childAccountRequired: false, remoteTelemetryDefault: false },
    },
    scenes: [
      {
        id: 'lantern-cover',
        kind: 'cover',
        title: '꺼진 등불의 아침',
        shortLabel: '시작',
        instruction: '표지를 열고 바람 마을의 지도를 만나세요.',
        narration: '아침이 되자 바람 마을 광장의 등불 하나가 보이지 않았어요.',
        visual: {
          motif: 'paper',
          palette: 'amber',
          alt: '빈 등불 걸이와 날아가는 지도 조각',
          truthStatus: 'fixture',
          decorations: ['moon', 'mountains', 'lantern', 'ribbons'],
        },
        textBlocks: [
          {
            id: 'lantern-text-cover',
            heading: '바람이 남긴 것',
            body: '지도지기 다온은 걸이 아래에서 파랑, 빨강, 흰색 리본 조각을 발견했어요.',
          },
        ],
        interactionIds: [],
        reasoningIds: [],
        connectionIds: [],
      },
      {
        id: 'lantern-map',
        kind: 'cover',
        title: '세 바람의 약속',
        shortLabel: '읽기',
        instruction: '지도 쪽지에서 리본의 수와 매듭 모양을 읽어 보세요.',
        narration:
          '지도 쪽지에는 같은 색 리본 두 개와 별 모양 매듭이 있는 길을 찾으라고 쓰여 있었어요.',
        visual: {
          motif: 'moon',
          palette: 'jade',
          alt: '세 색 리본과 별 모양 매듭이 그려진 쪽지',
          truthStatus: 'fixture',
          decorations: ['moon', 'ribbons'],
        },
        textBlocks: [
          {
            id: 'lantern-text-map',
            heading: '두 가지 조건',
            body: '색 하나만 보지 말고 리본의 수와 매듭 모양을 함께 비교해야 했어요.',
          },
        ],
        interactionIds: [],
        reasoningIds: [],
        connectionIds: [],
      },
      {
        id: 'lantern-search',
        kind: 'investigation',
        title: '리본이 가리킨 길',
        shortLabel: '찾기',
        instruction: '세 길의 리본 수와 매듭 모양을 비교해 쪽지와 맞는 길을 찾으세요.',
        narration: '강 길, 언덕 길, 돌담 길에는 서로 다른 리본이 바람에 흔들리고 있었어요.',
        visual: {
          motif: 'painting',
          palette: 'amber',
          alt: '색과 수가 다른 리본이 놓인 세 갈래 길',
          truthStatus: 'fixture',
          decorations: ['moon', 'mountains', 'stoneWall', 'lantern', 'ribbons'],
          baseAssetId: 'asset-lantern-base',
          detailAssetId: 'asset-lantern-detail',
        },
        textBlocks: [
          {
            id: 'lantern-text-search',
            heading: '지도 가장자리',
            body: '다온은 리본을 하나씩 세고 매듭의 뾰족한 모양을 살폈어요.',
          },
          {
            id: 'lantern-text-unlocked',
            heading: '렌즈가 밝힌 것',
            body: '돌담 아래 흰 리본 두 개 사이에서 별 모양 매듭이 반짝였어요.',
          },
        ],
        interactionIds: ['lantern-find-ribbon'],
        reasoningIds: [],
        connectionIds: [],
      },
      {
        id: 'lantern-reason',
        kind: 'reasoning',
        title: '등불은 왜 돌담에 있었을까',
        shortLabel: '생각',
        instruction: '찾은 리본과 지도 쪽지를 이어 가장 알맞은 설명을 고르세요.',
        narration: '돌담 길 끝에는 바람을 피해 단단히 묶인 등불 꾸러미가 있었어요.',
        visual: {
          motif: 'moon',
          palette: 'ink',
          alt: '돌담 곁에서 등불 꾸러미를 살피는 다온',
          truthStatus: 'fixture',
          decorations: ['moon', 'stoneWall', 'lantern', 'child'],
        },
        textBlocks: [
          {
            id: 'lantern-text-reason',
            heading: '단서를 이어 보기',
            body: '흰 리본 두 개는 길을, 별 모양 매듭은 같은 등불 꾸러미임을 알려 주었어요.',
          },
        ],
        interactionIds: [],
        reasoningIds: ['lantern-reasoning'],
        connectionIds: [],
      },
      {
        id: 'lantern-connect',
        kind: 'connection',
        title: '다음 지도를 보는 질문',
        shortLabel: '연결',
        instruction: '질문 카드를 열어 다른 그림을 살펴보는 순서를 확인하세요.',
        narration: '다온은 등불을 되찾고, 다음 지도에서도 특징을 둘씩 묶어 보기로 했어요.',
        visual: {
          motif: 'museum',
          palette: 'jade',
          alt: '등불을 켠 다온과 새 지도 질문 카드',
          truthStatus: 'fixture',
          decorations: ['moon', 'lantern', 'ribbons', 'child'],
        },
        textBlocks: [
          {
            id: 'lantern-text-connect',
            heading: '다음 관찰',
            body: '색, 수, 모양 가운데 서로 이어지는 두 특징을 찾으면 어떤 길이 보일까요?',
          },
        ],
        interactionIds: [],
        reasoningIds: [],
        connectionIds: ['lantern-connection'],
      },
    ],
    interactions: [
      {
        id: 'lantern-find-ribbon',
        sceneId: 'lantern-search',
        kind: 'findClue',
        prompt: '리본의 색과 수, 매듭 모양을 함께 비교하세요.',
        accessibleName: '바람 지도의 세 길 살펴보기',
        inputAdapters: ['lens', 'regionTap', 'keyboard', 'linearExplore'],
        pointerTarget: {
          shape: 'ellipse',
          centerXPercent: 63,
          centerYPercent: 67,
          radiusXPercent: 16,
          radiusYPercent: 20,
        },
        choices: [
          { id: 'lantern-river', label: '강 길: 파랑 리본 한 개와 둥근 매듭' },
          { id: 'lantern-hill', label: '언덕 길: 빨강 리본 두 개와 네모 매듭' },
          { id: 'lantern-wall', label: '돌담 길: 흰 리본 두 개와 별 모양 매듭' },
        ],
        correctChoiceId: 'lantern-wall',
        successFeedback: '흰 리본 두 개와 별 모양 매듭이 쪽지의 두 조건과 모두 맞아요.',
        retryFeedback: '괜찮아요. 리본의 색만 보지 말고 수와 매듭 모양도 함께 살펴보세요.',
        unlockTextIds: ['lantern-text-unlocked'],
        hintSteps: [
          { kind: 'word', text: '리본의 수와 매듭 모양을 함께 보세요.' },
          { kind: 'direction', text: '그림 오른쪽의 돌담 쪽으로 눈길을 옮겨 보세요.' },
          { kind: 'area', text: '돌담 아래 길의 리본 사이를 살펴보세요.' },
          { kind: 'direct', text: '흰 리본 두 개와 별 모양 매듭이 있는 돌담 길을 고르세요.' },
        ],
        completion: { minimumDiscoveries: 1 },
      },
    ],
    reasoningPrompts: [
      {
        id: 'lantern-reasoning',
        sceneId: 'lantern-reason',
        prompt: '돌담 길을 고를 수 있는 두 단서를 바르게 이은 것은 무엇인가요?',
        choices: [
          { id: 'lantern-choice-river', label: '파랑 리본 한 개와 둥근 매듭' },
          { id: 'lantern-choice-wall', label: '흰 리본 두 개와 별 모양 매듭' },
          { id: 'lantern-choice-hill', label: '빨강 리본 두 개와 네모 매듭' },
        ],
        correctChoiceId: 'lantern-choice-wall',
        evidenceInteractionIds: ['lantern-find-ribbon'],
        successFeedback: '리본의 수와 별 모양 매듭이 지도 쪽지와 모두 맞아요.',
        retryFeedback: '찾기 장면에서 함께 확인한 두 특징을 다시 떠올려 보세요.',
      },
    ],
    connectionCards: [
      {
        id: 'lantern-connection',
        sceneId: 'lantern-connect',
        title: '특징을 둘씩 묶어 보는 질문',
        body: '이 카드는 비공개 기능 검증용 창작 설명입니다. 다음 그림에서 색, 수, 모양 중 이어지는 두 특징을 찾아보세요.',
        sourceClaimIds: ['lantern-claim-fixture'],
        truthStatus: 'fixture',
      },
    ],
    rights: [
      {
        id: 'lantern-rights-story',
        subjectType: 'text',
        subjectId: 'book-lantern-demo',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트의 비공개 제작 검증용 창작 fixture',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes: '실제 문화유산, 기관, 인물을 나타내지 않습니다.',
        coveredSubjectIds: ['book-lantern-demo'],
      },
      {
        id: 'lantern-rights-art',
        subjectType: 'visual',
        subjectId: 'asset-lantern-scene-files',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트가 직접 만든 비공개 fixture SVG',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes: '외부 원본을 사용하지 않은 base와 detail 자산입니다.',
        coveredSubjectIds: ['asset-lantern-base', 'asset-lantern-detail'],
      },
      {
        id: 'lantern-rights-audio',
        subjectType: 'audio',
        subjectId: 'asset-lantern-timing',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트가 코드로 생성한 비공개 타이밍 fixture 음원',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes:
          '재생, seek, 속도, segment 동기화 검증용 저음량 음계이며 검수 낭독이나 한국어 발화가 아닙니다.',
        coveredSubjectIds: ['asset-lantern-timing'],
      },
      {
        id: 'lantern-rights-claim',
        subjectType: 'claim',
        subjectId: 'lantern-claim-fixture',
        license: 'Apache-2.0',
        sourceUrl: null,
        attribution: 'Soombook 프로젝트의 기능 검증 문장',
        commercialUse: true,
        modificationAllowed: true,
        approvalStatus: 'fixture',
        notes: '문화 사실이 아닌 fixture 범위 주장입니다.',
        coveredSubjectIds: ['lantern-claim-fixture'],
      },
    ],
    claims: [
      {
        id: 'lantern-claim-fixture',
        statement:
          '등불 지도 이야기는 반복 제작 검증용 창작 fixture이며 실제 문화 사실을 주장하지 않는다.',
        sourceTitle: 'Soombook 내부 비공개 fixture 장부',
        sourceUrl: null,
        checkedAt: '2026-08-09',
        reviewStatus: 'fixture',
        kind: 'fixture',
        scope: 'fixture',
        caveats: ['실제 문화유산 사실이나 해석으로 사용할 수 없습니다.'],
        sourceEvidenceRefs: [],
        audienceTextRefs: ['lantern-text-connect'],
        recheckTriggers: ['연결 카드 문구 변경'],
      },
    ],
    assets: [
      {
        id: 'asset-lantern-base',
        kind: 'image',
        path: 'assets/lantern-base.svg',
        rightsRecordId: 'lantern-rights-art',
        integrity: 'sha256-47622f8dda1d928167656f8b49f54c94b1d3efcc26ca8d86be4d4a7d4174ed40',
        alt: '리본이 놓인 바람 마을의 세 갈래 길',
        role: 'storyIllustration',
        truthStatus: 'fixture',
        derivedFromAssetIds: [],
      },
      {
        id: 'asset-lantern-detail',
        kind: 'image',
        path: 'assets/lantern-detail.svg',
        rightsRecordId: 'lantern-rights-art',
        integrity: 'sha256-7d619177f3e85d21f7a3e591ca6bddde75e5b6c2a5cde6b2bd94c59fc071d85d',
        alt: '돌담 아래 흰 리본 두 개와 별 모양 매듭의 상세 장면',
        role: 'storyIllustration',
        truthStatus: 'fixture',
        derivedFromAssetIds: ['asset-lantern-base'],
      },
      {
        id: 'asset-lantern-timing',
        kind: 'audio',
        path: 'assets/lantern-timing.wav',
        rightsRecordId: 'lantern-rights-audio',
        integrity: 'sha256-d8aa2370280a494e74b8e7b47c1fb08979dc0f374bbc92aa13c7f4f1fed1601d',
        alt: '오디오 동기화 검증용 4초 음계',
        role: 'fixtureTiming',
        truthStatus: 'fixture',
        derivedFromAssetIds: [],
      },
    ],
    audioTracks: [
      {
        id: 'audio-lantern-cover',
        sceneId: 'lantern-cover',
        assetId: 'asset-lantern-timing',
        durationMs: 4_000,
        segments: [
          {
            id: 'audio-lantern-cover-text',
            textId: 'lantern-text-cover',
            startMs: 0,
            endMs: 4_000,
          },
        ],
      },
      {
        id: 'audio-lantern-map',
        sceneId: 'lantern-map',
        assetId: 'asset-lantern-timing',
        durationMs: 4_000,
        segments: [
          {
            id: 'audio-lantern-map-text',
            textId: 'lantern-text-map',
            startMs: 0,
            endMs: 4_000,
          },
        ],
      },
      {
        id: 'audio-lantern-search',
        sceneId: 'lantern-search',
        assetId: 'asset-lantern-timing',
        durationMs: 4_000,
        segments: [
          {
            id: 'audio-lantern-search-visible',
            textId: 'lantern-text-search',
            startMs: 0,
            endMs: 2_000,
          },
          {
            id: 'audio-lantern-search-unlocked',
            textId: 'lantern-text-unlocked',
            startMs: 2_000,
            endMs: 4_000,
          },
        ],
      },
      {
        id: 'audio-lantern-reason',
        sceneId: 'lantern-reason',
        assetId: 'asset-lantern-timing',
        durationMs: 4_000,
        segments: [
          {
            id: 'audio-lantern-reason-text',
            textId: 'lantern-text-reason',
            startMs: 0,
            endMs: 4_000,
          },
        ],
      },
      {
        id: 'audio-lantern-connect',
        sceneId: 'lantern-connect',
        assetId: 'asset-lantern-timing',
        durationMs: 4_000,
        segments: [
          {
            id: 'audio-lantern-connect-text',
            textId: 'lantern-text-connect',
            startMs: 0,
            endMs: 4_000,
          },
        ],
      },
    ],
  };
}
