import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';

import { bookPackSchema } from '../packages/book-schema/src/bookPackSchema.ts';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUTPUT = path.join(ROOT, 'packages/book-schema/src/bookPackValidator.generated.mjs');
const HEADER = '// Generated by scripts/generateBookPackValidator.mjs. Do not edit by hand.\n';

function generateValidator() {
  const ajv = new Ajv2020({
    allErrors: true,
    code: { esm: true, source: true },
    strict: true,
  });
  const validate = ajv.compile(bookPackSchema);
  const runtimeImports = new Map();
  const source = standaloneCode(ajv, validate).replace(
    /const (\w+) = require\("([^"]+)"\)\.default;/gu,
    (_match, variableName, moduleName) => {
      let importName = runtimeImports.get(moduleName);
      if (!importName) {
        importName = `ajvRuntime${runtimeImports.size}`;
        runtimeImports.set(moduleName, importName);
      }
      return `const ${variableName} = typeof ${importName} === "function" ? ${importName} : ${importName}.default;`;
    },
  );
  const imports = [...runtimeImports.entries()]
    .map(([moduleName, importName]) => `import ${importName} from '${moduleName}.js';`)
    .join('\n');
  return `${HEADER}${imports}\n${source}\n`;
}

const generated = generateValidator();
if (process.argv.includes('--write')) {
  await writeFile(OUTPUT, generated, 'utf8');
  console.log('BookPack standalone validator 동기화 완료');
} else if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = await readFile(OUTPUT, 'utf8');
  } catch {
    // 누락 파일은 아래 drift 오류로 처리합니다.
  }
  if (current !== generated) {
    console.error('BookPack standalone validator drift: npm run validator:sync를 실행하세요.');
    process.exitCode = 1;
  } else {
    console.log('BookPack standalone validator 검증 통과');
  }
} else {
  throw new Error('--write 또는 --check가 필요합니다.');
}
