export const bookPackSchema = {
  $id: 'https://soombook.dev/schema/book-pack-1.0.0.json',
  type: 'object',
  additionalProperties: false,
  required: [
    'manifest',
    'book',
    'scenes',
    'interactions',
    'reasoningPrompts',
    'connectionCards',
    'rights',
    'claims',
    'assets',
    'audioTracks',
  ],
  properties: {
    manifest: {
      type: 'object',
      additionalProperties: false,
      required: [
        'formatVersion',
        'packVersion',
        'id',
        'slug',
        'title',
        'status',
        'locale',
        'minReaderVersion',
        'entrySceneId',
        'sceneOrder',
        'completion',
      ],
      properties: {
        formatVersion: { const: '1.0.0' },
        packVersion: { type: 'string', pattern: '^[0-9]+\\.[0-9]+\\.[0-9]+$' },
        id: { type: 'string', minLength: 1 },
        slug: { type: 'string', pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' },
        title: { type: 'string', minLength: 1 },
        status: {
          enum: ['fixture', 'internal', 'review', 'published', 'withdrawn'],
        },
        locale: { const: 'ko-KR' },
        minReaderVersion: { type: 'string', pattern: '^[0-9]+\\.[0-9]+\\.[0-9]+$' },
        entrySceneId: { type: 'string', minLength: 1 },
        sceneOrder: {
          type: 'array',
          minItems: 1,
          uniqueItems: true,
          items: { type: 'string', minLength: 1 },
        },
        completion: {
          type: 'object',
          additionalProperties: false,
          required: [
            'requiredConnectionIds',
            'requiredInteractionIds',
            'requiredReasoningIds',
            'review',
          ],
          properties: {
            requiredConnectionIds: { $ref: '#/$defs/idList' },
            requiredInteractionIds: { $ref: '#/$defs/idList' },
            requiredReasoningIds: { $ref: '#/$defs/idList' },
            review: {
              type: 'object',
              additionalProperties: false,
              required: ['recallPrompt', 'recallCards', 'treasure'],
              properties: {
                recallPrompt: { type: 'string', minLength: 1 },
                recallCards: {
                  type: 'array',
                  minItems: 1,
                  uniqueItems: true,
                  items: { $ref: '#/$defs/completionRecallCard' },
                },
                treasure: { $ref: '#/$defs/completionTreasureCard' },
              },
            },
          },
        },
      },
    },
    book: {
      type: 'object',
      required: ['audience', 'summary', 'learningGoals', 'readingModes', 'privacy'],
      additionalProperties: false,
      properties: {
        audience: {
          type: 'object',
          required: ['grade', 'independentReadingMinutes'],
          additionalProperties: false,
          properties: {
            grade: { const: 3 },
            independentReadingMinutes: { type: 'number', minimum: 1, maximum: 60 },
          },
        },
        summary: { type: 'string', minLength: 1 },
        learningGoals: {
          type: 'array',
          minItems: 1,
          items: { type: 'string', minLength: 1 },
        },
        readingModes: {
          type: 'array',
          minItems: 1,
          uniqueItems: true,
          items: { enum: ['direct', 'guided', 'listen'] },
        },
        privacy: {
          type: 'object',
          required: ['childAccountRequired', 'remoteTelemetryDefault'],
          additionalProperties: false,
          properties: {
            childAccountRequired: { const: false },
            remoteTelemetryDefault: { const: false },
          },
        },
      },
    },
    scenes: {
      type: 'array',
      minItems: 1,
      items: { $ref: '#/$defs/scene' },
    },
    interactions: {
      type: 'array',
      items: { $ref: '#/$defs/interaction' },
    },
    reasoningPrompts: {
      type: 'array',
      items: { $ref: '#/$defs/reasoningPrompt' },
    },
    connectionCards: {
      type: 'array',
      items: { $ref: '#/$defs/connectionCard' },
    },
    rights: {
      type: 'array',
      minItems: 1,
      items: { $ref: '#/$defs/rightsRecord' },
    },
    claims: {
      type: 'array',
      items: { $ref: '#/$defs/claimRecord' },
    },
    assets: {
      type: 'array',
      minItems: 1,
      items: { $ref: '#/$defs/assetRecord' },
    },
    audioTracks: {
      type: 'array',
      items: { $ref: '#/$defs/audioTrack' },
    },
    reviewRecords: {
      type: 'array',
      items: { $ref: '#/$defs/reviewRecord' },
    },
  },
  $defs: {
    completionRecallCard: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'text'],
      properties: {
        id: { type: 'string', minLength: 1 },
        text: { type: 'string', minLength: 1 },
      },
    },
    completionTreasureCard: {
      type: 'object',
      additionalProperties: false,
      required: ['interactionId', 'title', 'body'],
      properties: {
        interactionId: { type: 'string', minLength: 1 },
        title: { type: 'string', minLength: 1 },
        body: { type: 'string', minLength: 1 },
      },
    },
    idList: {
      type: 'array',
      uniqueItems: true,
      items: { type: 'string', minLength: 1 },
    },
    textBlock: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'body'],
      properties: {
        id: { type: 'string', minLength: 1 },
        heading: { type: 'string', minLength: 1 },
        body: { type: 'string', minLength: 1 },
      },
    },
    visual: {
      type: 'object',
      additionalProperties: false,
      required: ['motif', 'palette', 'alt'],
      properties: {
        motif: { enum: ['paper', 'painting', 'moon', 'museum'] },
        palette: { enum: ['ink', 'indigo', 'amber', 'jade'] },
        alt: { type: 'string', minLength: 1 },
        truthStatus: {
          enum: [
            'fiction',
            'fixture',
            'unverifiedClaim',
            'verifiedSource',
            'derivedFromVerifiedSource',
          ],
        },
        decorations: {
          type: 'array',
          uniqueItems: true,
          items: {
            enum: [
              'moon',
              'mountains',
              'pine',
              'tiger',
              'child',
              'lantern',
              'stoneWall',
              'ribbons',
            ],
          },
        },
        baseAssetId: { type: 'string', minLength: 1 },
        detailAssetId: { type: 'string', minLength: 1 },
      },
    },
    scene: {
      type: 'object',
      additionalProperties: false,
      required: [
        'id',
        'kind',
        'title',
        'shortLabel',
        'instruction',
        'narration',
        'visual',
        'textBlocks',
        'interactionIds',
        'reasoningIds',
        'connectionIds',
      ],
      properties: {
        id: { type: 'string', minLength: 1 },
        kind: { enum: ['cover', 'investigation', 'reasoning', 'connection'] },
        title: { type: 'string', minLength: 1 },
        shortLabel: { type: 'string', minLength: 1 },
        instruction: { type: 'string', minLength: 1 },
        narration: { type: 'string', minLength: 1 },
        visual: { $ref: '#/$defs/visual' },
        textBlocks: {
          type: 'array',
          minItems: 1,
          items: { $ref: '#/$defs/textBlock' },
        },
        interactionIds: { $ref: '#/$defs/idList' },
        reasoningIds: { $ref: '#/$defs/idList' },
        connectionIds: { $ref: '#/$defs/idList' },
      },
    },
    interaction: {
      type: 'object',
      additionalProperties: false,
      required: [
        'id',
        'sceneId',
        'kind',
        'prompt',
        'accessibleName',
        'inputAdapters',
        'choices',
        'correctChoiceId',
        'successFeedback',
        'retryFeedback',
        'unlockTextIds',
        'hintSteps',
        'completion',
      ],
      properties: {
        id: { type: 'string', minLength: 1 },
        sceneId: { type: 'string', minLength: 1 },
        kind: { const: 'findClue' },
        prompt: { type: 'string', minLength: 1 },
        accessibleName: { type: 'string', minLength: 1 },
        inputAdapters: {
          type: 'array',
          minItems: 2,
          uniqueItems: true,
          items: { enum: ['lens', 'regionTap', 'keyboard', 'linearExplore'] },
        },
        pointerTarget: { $ref: '#/$defs/interactionPointerTarget' },
        choices: {
          type: 'array',
          minItems: 2,
          uniqueItems: true,
          items: { $ref: '#/$defs/reasoningChoice' },
        },
        correctChoiceId: { type: 'string', minLength: 1 },
        successFeedback: { type: 'string', minLength: 1 },
        retryFeedback: { type: 'string', minLength: 1 },
        unlockTextIds: { $ref: '#/$defs/idList' },
        hintSteps: {
          type: 'array',
          minItems: 1,
          items: { $ref: '#/$defs/hintStep' },
        },
        completion: {
          type: 'object',
          additionalProperties: false,
          required: ['minimumDiscoveries'],
          properties: {
            minimumDiscoveries: { type: 'integer', minimum: 1 },
          },
        },
      },
    },
    interactionPointerTarget: {
      type: 'object',
      additionalProperties: false,
      required: ['shape', 'centerXPercent', 'centerYPercent', 'radiusXPercent', 'radiusYPercent'],
      properties: {
        shape: { const: 'ellipse' },
        centerXPercent: { type: 'number', minimum: 0, maximum: 100 },
        centerYPercent: { type: 'number', minimum: 0, maximum: 100 },
        radiusXPercent: { type: 'number', exclusiveMinimum: 0, maximum: 100 },
        radiusYPercent: { type: 'number', exclusiveMinimum: 0, maximum: 100 },
      },
    },
    reasoningChoice: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'label'],
      properties: {
        id: { type: 'string', minLength: 1 },
        label: { type: 'string', minLength: 1 },
      },
    },
    hintStep: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'text'],
      properties: {
        kind: { enum: ['word', 'direction', 'area', 'direct'] },
        text: { type: 'string', minLength: 1 },
      },
    },
    reasoningPrompt: {
      type: 'object',
      additionalProperties: false,
      required: [
        'id',
        'sceneId',
        'prompt',
        'choices',
        'correctChoiceId',
        'evidenceInteractionIds',
        'successFeedback',
        'retryFeedback',
      ],
      properties: {
        id: { type: 'string', minLength: 1 },
        sceneId: { type: 'string', minLength: 1 },
        prompt: { type: 'string', minLength: 1 },
        choices: {
          type: 'array',
          minItems: 2,
          uniqueItems: true,
          items: { $ref: '#/$defs/reasoningChoice' },
        },
        correctChoiceId: { type: 'string', minLength: 1 },
        evidenceInteractionIds: { $ref: '#/$defs/idList' },
        successFeedback: { type: 'string', minLength: 1 },
        retryFeedback: { type: 'string', minLength: 1 },
      },
    },
    connectionCard: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'sceneId', 'title', 'body', 'sourceClaimIds'],
      properties: {
        id: { type: 'string', minLength: 1 },
        sceneId: { type: 'string', minLength: 1 },
        title: { type: 'string', minLength: 1 },
        body: { type: 'string', minLength: 1 },
        sourceClaimIds: { $ref: '#/$defs/idList' },
        truthStatus: {
          enum: [
            'fiction',
            'fixture',
            'unverifiedClaim',
            'verifiedSource',
            'derivedFromVerifiedSource',
          ],
        },
        sourcePresentation: { $ref: '#/$defs/sourcePresentation' },
      },
    },
    sourcePresentation: {
      type: 'object',
      additionalProperties: false,
      required: ['institution', 'identifier', 'sourceUrl', 'license', 'attribution'],
      properties: {
        institution: { type: 'string', minLength: 1 },
        identifier: { type: ['string', 'null'] },
        sourceUrl: { type: 'string', minLength: 1 },
        license: { type: 'string', minLength: 1 },
        attribution: { type: 'string', minLength: 1 },
      },
    },
    rightsRecord: {
      type: 'object',
      additionalProperties: false,
      required: [
        'id',
        'subjectType',
        'subjectId',
        'license',
        'sourceUrl',
        'attribution',
        'commercialUse',
        'modificationAllowed',
        'approvalStatus',
        'notes',
      ],
      properties: {
        id: { type: 'string', minLength: 1 },
        subjectType: { enum: ['text', 'visual', 'audio', 'claim'] },
        subjectId: { type: 'string', minLength: 1 },
        license: { type: 'string', minLength: 1 },
        sourceUrl: { type: ['string', 'null'] },
        attribution: { type: 'string' },
        commercialUse: { type: 'boolean' },
        modificationAllowed: { type: 'boolean' },
        approvalStatus: {
          enum: ['fixture', 'pending', 'approved', 'rejected', 'suspended', 'withdrawn'],
        },
        notes: { type: 'string' },
        coveredSubjectIds: { $ref: '#/$defs/idList' },
        provenance: { $ref: '#/$defs/rightsProvenance' },
      },
    },
    sourceSnapshot: {
      type: 'object',
      additionalProperties: false,
      required: ['status', 'evidenceRef', 'sha256', 'capturedAt'],
      properties: {
        status: { enum: ['pending', 'captured'] },
        evidenceRef: { type: 'string', minLength: 1 },
        sha256: { type: ['string', 'null'], pattern: '^sha256-[0-9a-f]{64}$' },
        capturedAt: {
          type: ['string', 'null'],
          pattern:
            '^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$',
        },
      },
    },
    rightsProvenance: {
      type: 'object',
      additionalProperties: false,
      required: [
        'sourceInstitution',
        'sourceIdentifier',
        'licenseUrl',
        'transformations',
        'derivedFromAssetIds',
        'sourceSnapshot',
        'approvalEvidenceDigest',
        'ingestReceiptDigest',
        'approvalLifecycle',
        'recheckTriggers',
      ],
      properties: {
        sourceInstitution: { type: 'string', minLength: 1 },
        sourceIdentifier: { type: ['string', 'null'] },
        licenseUrl: { type: ['string', 'null'] },
        transformations: {
          type: 'array',
          uniqueItems: true,
          items: { type: 'string', minLength: 1 },
        },
        derivedFromAssetIds: { $ref: '#/$defs/idList' },
        sourceSnapshot: { $ref: '#/$defs/sourceSnapshot' },
        approvalEvidenceDigest: {
          type: ['string', 'null'],
          pattern: '^sha256-[0-9a-f]{64}$',
        },
        ingestReceiptDigest: {
          type: ['string', 'null'],
          pattern: '^sha256-[0-9a-f]{64}$',
        },
        approvalLifecycle: {
          type: 'object',
          additionalProperties: false,
          required: ['state', 'nextReviewAt'],
          properties: {
            state: { enum: ['pending', 'active', 'suspended', 'withdrawn'] },
            nextReviewAt: {
              type: ['string', 'null'],
              pattern:
                '^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$',
            },
          },
        },
        recheckTriggers: {
          type: 'array',
          minItems: 1,
          uniqueItems: true,
          items: { type: 'string', minLength: 1 },
        },
        verifiedSourceFiles: {
          type: 'array',
          minItems: 1,
          uniqueItems: true,
          items: {
            type: 'object',
            additionalProperties: false,
            required: ['sourceCandidateId', 'sourceSha256', 'sourceEvidenceRef'],
            properties: {
              sourceCandidateId: { type: 'string', minLength: 1 },
              sourceSha256: { type: 'string', pattern: '^sha256-[0-9a-f]{64}$' },
              sourceEvidenceRef: { type: 'string', minLength: 1 },
            },
          },
        },
      },
    },
    claimRecord: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'statement', 'sourceTitle', 'sourceUrl', 'checkedAt', 'reviewStatus'],
      properties: {
        id: { type: 'string', minLength: 1 },
        statement: { type: 'string', minLength: 1 },
        sourceTitle: { type: 'string', minLength: 1 },
        sourceUrl: { type: ['string', 'null'] },
        checkedAt: {
          type: 'string',
          pattern: '^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])$',
        },
        reviewStatus: { enum: ['fixture', 'pending', 'approved', 'rejected'] },
        kind: {
          enum: [
            'fixture',
            'fictionEvent',
            'storyInterpretation',
            'educationalFact',
            'museumMetadata',
            'licenseStatement',
            'safetyStatement',
          ],
        },
        scope: {
          enum: [
            'fixture',
            'storyOnly',
            'storySimplification',
            'objectOnly',
            'genreInterpretation',
            'licenseOnly',
          ],
        },
        caveats: {
          type: 'array',
          uniqueItems: true,
          items: { type: 'string', minLength: 1 },
        },
        sourceEvidenceRefs: {
          type: 'array',
          uniqueItems: true,
          items: { type: 'string', minLength: 1 },
        },
        audienceTextRefs: { $ref: '#/$defs/idList' },
        recheckTriggers: {
          type: 'array',
          uniqueItems: true,
          items: { type: 'string', minLength: 1 },
        },
      },
    },
    assetRecord: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'kind', 'path', 'rightsRecordId', 'integrity', 'alt'],
      properties: {
        id: { type: 'string', minLength: 1 },
        kind: { enum: ['cssArtwork', 'image', 'audio', 'font'] },
        path: { type: ['string', 'null'] },
        rightsRecordId: { type: 'string', minLength: 1 },
        integrity: { type: ['string', 'null'] },
        alt: { type: 'string', minLength: 1 },
        role: {
          enum: [
            'storyIllustration',
            'sourceOriginal',
            'sourceDetail',
            'narrationAudio',
            'fixtureTiming',
            'ui',
          ],
        },
        truthStatus: {
          enum: [
            'fiction',
            'fixture',
            'unverifiedClaim',
            'verifiedSource',
            'derivedFromVerifiedSource',
          ],
        },
        derivedFromAssetIds: { $ref: '#/$defs/idList' },
        sourceLineage: {
          type: 'object',
          additionalProperties: false,
          required: [
            'sourceCandidateId',
            'sourceSha256',
            'sourceEvidenceRef',
            'derivativePlanDigest',
            'ingestReceiptDigest',
          ],
          properties: {
            sourceCandidateId: { type: 'string', minLength: 1 },
            sourceSha256: { type: 'string', pattern: '^sha256-[0-9a-f]{64}$' },
            sourceEvidenceRef: { type: 'string', minLength: 1 },
            derivativePlanDigest: { type: 'string', pattern: '^sha256-[0-9a-f]{64}$' },
            ingestReceiptDigest: { type: 'string', pattern: '^sha256-[0-9a-f]{64}$' },
          },
        },
      },
    },
    audioSegment: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'textId', 'startMs', 'endMs'],
      properties: {
        id: { type: 'string', minLength: 1 },
        textId: { type: 'string', minLength: 1 },
        startMs: { type: 'number', minimum: 0 },
        endMs: { type: 'number', exclusiveMinimum: 0 },
      },
    },
    audioTrack: {
      type: 'object',
      additionalProperties: false,
      required: ['id', 'sceneId', 'assetId', 'durationMs', 'segments'],
      properties: {
        id: { type: 'string', minLength: 1 },
        sceneId: { type: 'string', minLength: 1 },
        assetId: { type: 'string', minLength: 1 },
        durationMs: { type: 'number', exclusiveMinimum: 0 },
        segments: {
          type: 'array',
          minItems: 1,
          items: { $ref: '#/$defs/audioSegment' },
        },
      },
    },
    reviewRecord: {
      type: 'object',
      additionalProperties: false,
      required: [
        'id',
        'domain',
        'subjectType',
        'subjectId',
        'status',
        'reviewerRef',
        'reviewedAt',
        'subjectDigest',
        'packVersion',
        'notes',
      ],
      properties: {
        id: { type: 'string', minLength: 1 },
        domain: { enum: ['rights', 'culture', 'education', 'audio', 'accessibility'] },
        subjectType: { enum: ['pack', 'rights', 'claim', 'asset', 'audioTrack'] },
        subjectId: { type: 'string', minLength: 1 },
        status: { enum: ['pending', 'approved', 'rejected'] },
        reviewerRef: { type: ['string', 'null'] },
        reviewedAt: {
          type: ['string', 'null'],
          pattern: '^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])$',
        },
        subjectDigest: { type: ['string', 'null'], pattern: '^sha256-[0-9a-f]{64}$' },
        packVersion: { type: 'string', pattern: '^[0-9]+\\.[0-9]+\\.[0-9]+$' },
        notes: { type: 'string' },
      },
    },
  },
} as const;
